"""The initial migration must build exactly the schema the models describe."""

from __future__ import annotations

from pathlib import Path

import pytest
from alembic.autogenerate import compare_metadata
from alembic.config import Config
from alembic.migration import MigrationContext
from sqlalchemy import create_engine, inspect

from alembic import command
from app import models  # noqa: F401  — populates Base.metadata
from app.config import get_settings
from app.db import Base, is_sqlite

PROJECT_ROOT = Path(__file__).resolve().parent.parent
VERSION_TABLE = "alembic_version"


@pytest.fixture
def migration_url(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> str:
    """A private SQLite file so migrations never touch the configured database."""
    url = f"sqlite+pysqlite:///{tmp_path / 'migrations.db'}"
    monkeypatch.setenv("DATABASE_URL", url)
    get_settings.cache_clear()
    try:
        yield url
    finally:
        get_settings.cache_clear()


@pytest.fixture
def alembic_config() -> Config:
    return Config(str(PROJECT_ROOT / "alembic.ini"))


def table_names(url: str) -> set[str]:
    engine = create_engine(url)
    try:
        return set(inspect(engine).get_table_names())
    finally:
        engine.dispose()


def test_upgrade_downgrade_upgrade_is_idempotent(
    alembic_config: Config, migration_url: str
) -> None:
    command.upgrade(alembic_config, "head")
    after_first_upgrade = table_names(migration_url)

    command.downgrade(alembic_config, "base")
    after_downgrade = table_names(migration_url)

    command.upgrade(alembic_config, "head")

    assert after_first_upgrade == set(Base.metadata.tables) | {VERSION_TABLE}
    assert after_downgrade == {VERSION_TABLE}
    assert table_names(migration_url) == after_first_upgrade


def test_schema_matches_the_models(alembic_config: Config, migration_url: str) -> None:
    """The equivalent of ``alembic check``: no drift between migration and models."""
    command.upgrade(alembic_config, "head")

    engine = create_engine(migration_url)
    try:
        with engine.connect() as connection:
            context = MigrationContext.configure(
                connection,
                opts={"compare_type": True, "render_as_batch": is_sqlite(migration_url)},
            )
            assert compare_metadata(context, Base.metadata) == []
    finally:
        engine.dispose()


def test_downgrade_drops_indexes_only_with_a_written_reason() -> None:
    """Some dialects refuse to drop an index while a foreign key still needs the column.

    ``drop_table`` removes indexes on its own, so an autogenerated ``drop_index`` in a
    downgrade is usually a portability bug. Where one is genuinely required — dropping a
    single column in SQLite's batch mode, for instance — the migration has to say why.
    """
    marker = "drop_index is safe here:"
    for migration in (PROJECT_ROOT / "alembic" / "versions").glob("*.py"):
        content = migration.read_text()
        downgrade_body = content.split("def downgrade")[-1]
        if "drop_index" in downgrade_body:
            assert marker in downgrade_body, (
                f"{migration.name}: explain why dropping the index is safe "
                f'by writing "{marker} …" next to it'
            )


def test_migration_does_not_import_application_code() -> None:
    """Migrations must keep running even when the models move on."""
    for migration in (PROJECT_ROOT / "alembic" / "versions").glob("*.py"):
        assert "app." not in migration.read_text(), migration.name


def test_migrations_survive_a_database_that_holds_data(
    alembic_config: Config, migration_url: str
) -> None:
    """A rebuild of ``users`` must not trip over the rows that reference it.

    SQLite has no ``ALTER COLUMN``: Alembic rebuilds the table and drops the old one,
    which enforced foreign keys refuse while sessions or chores still point at it. An
    empty database never notices — a real one fails on the first upgrade.
    """
    command.upgrade(alembic_config, "0003")

    engine = create_engine(migration_url)
    try:
        with engine.begin() as connection:
            connection.exec_driver_sql(
                "INSERT INTO households (id, name, type, join_code, currency,"
                " created_at, updated_at)"
                " VALUES (1, 'WG', 'wg', 'AAAABBBBCCCC', 'EUR', '2026-01-01', '2026-01-01')"
            )
            connection.exec_driver_sql(
                "INSERT INTO users (id, email, password_hash, first_name, locale,"
                " household_id, role, points, must_change_password, is_active,"
                " created_at, updated_at)"
                " VALUES (1, 'alex', 'x', 'Alex', 'de', 1, 'admin', 0, 0, 1,"
                " '2026-01-01', '2026-01-01')"
            )
            connection.exec_driver_sql(
                "INSERT INTO sessions (id, token_hash, user_id, last_seen_at, expires_at,"
                " created_at, updated_at)"
                " VALUES (1, 'hash', 1, '2026-01-01', '2027-01-01',"
                " '2026-01-01', '2026-01-01')"
            )
            connection.exec_driver_sql(
                "INSERT INTO chores (id, household_id, title, points, rotation_seconds,"
                " fixed, member_order, current_user_id, created_at, updated_at)"
                " VALUES (1, 1, 'Bad', 2, 604800, 0, '[1]', 1,"
                " '2026-01-01', '2026-01-01')"
            )

        command.upgrade(alembic_config, "head")

        with engine.connect() as connection:
            username = connection.exec_driver_sql("SELECT username FROM users").scalar()
            chores = connection.exec_driver_sql("SELECT COUNT(*) FROM chores").scalar()
            sessions = connection.exec_driver_sql("SELECT COUNT(*) FROM sessions").scalar()
            broken = connection.exec_driver_sql("PRAGMA foreign_key_check").all()
    finally:
        engine.dispose()

    # The previous login name carries over, and nothing else was lost on the way.
    assert username == "alex"
    assert (chores, sessions) == (1, 1)
    assert broken == []


def test_only_real_addresses_survive_in_the_email_column(
    alembic_config: Config, migration_url: str
) -> None:
    """Login names carried over by 0004 must not masquerade as addresses."""
    command.upgrade(alembic_config, "0004")

    engine = create_engine(migration_url)
    try:
        with engine.begin() as connection:
            for index, (username, email) in enumerate(
                [("jayw", "jayw"), ("bea", "bea@wg.example"), ("cem", "cem@wg")], start=1
            ):
                connection.exec_driver_sql(
                    "INSERT INTO users (id, username, email, password_hash, first_name,"
                    " locale, role, points, must_change_password, is_active,"
                    " created_at, updated_at)"
                    f" VALUES ({index}, '{username}', '{email}', 'x', 'Test', 'de',"
                    " 'member', 0, 0, 1, '2026-01-01', '2026-01-01')"
                )

        command.upgrade(alembic_config, "head")

        with engine.connect() as connection:
            rows = dict(connection.exec_driver_sql("SELECT username, email FROM users").all())
    finally:
        engine.dispose()

    assert rows["jayw"] is None, "a login name without @ is not an address"
    assert rows["bea"] == "bea@wg.example"
    # Loose on purpose: a home network address without a dot stays valid.
    assert rows["cem"] == "cem@wg"
