"""initial

Revision ID: 0001
Revises:
Create Date: 2026-08-02 23:19:38.518468

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "households",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "type",
            sa.Enum("wg", "couple", "family", name="household_type", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("image_file", sa.String(length=128), nullable=True),
        sa.Column("join_code", sa.String(length=12), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_households")),
    )
    with op.batch_alter_table("households", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_households_join_code"), ["join_code"], unique=True)

    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=80), nullable=False),
        sa.Column("last_name", sa.String(length=80), nullable=True),
        sa.Column("avatar_file", sa.String(length=128), nullable=True),
        sa.Column("locale", sa.String(length=8), nullable=False),
        sa.Column("household_id", sa.Integer(), nullable=True),
        sa.Column(
            "role",
            sa.Enum("admin", "member", name="user_role", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("points >= 0", name=op.f("ck_users_points_non_negative")),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
            name=op.f("fk_users_household_id_households"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_household_id"), ["household_id"], unique=False)

    op.create_table(
        "chores",
        sa.Column("household_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("rotation_seconds", sa.Integer(), nullable=False),
        sa.Column("fixed", sa.Boolean(), nullable=False),
        sa.Column("member_order", sa.JSON(), nullable=False),
        sa.Column("current_user_id", sa.Integer(), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_done_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("points >= 0", name=op.f("ck_chores_points_non_negative")),
        sa.ForeignKeyConstraint(
            ["current_user_id"],
            ["users.id"],
            name=op.f("fk_chores_current_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
            name=op.f("fk_chores_household_id_households"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chores")),
    )
    with op.batch_alter_table("chores", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_chores_current_user_id"), ["current_user_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_chores_due_at"), ["due_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_chores_household_id"), ["household_id"], unique=False)

    op.create_table(
        "feed_events",
        sa.Column("household_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=40), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("reference_type", sa.String(length=40), nullable=True),
        sa.Column("reference_id", sa.Integer(), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_feed_events_actor_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
            name=op.f("fk_feed_events_household_id_households"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feed_events")),
    )
    with op.batch_alter_table("feed_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_feed_events_actor_id"), ["actor_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_feed_events_household_id"), ["household_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_feed_events_type"), ["type"], unique=False)

    op.create_table(
        "notifications",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=40), nullable=False),
        sa.Column("title_key", sa.String(length=80), nullable=False),
        sa.Column("body_key", sa.String(length=80), nullable=True),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("reference_type", sa.String(length=40), nullable=True),
        sa.Column("reference_id", sa.Integer(), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_notifications_read_at"), ["read_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_notifications_user_id"), ["user_id"], unique=False)

    op.create_table(
        "sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sessions_expires_at"), ["expires_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_sessions_token_hash"), ["token_hash"], unique=True)
        batch_op.create_index(batch_op.f("ix_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "settlement_periods",
        sa.Column("household_id", sa.Integer(), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_by_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["closed_by_id"],
            ["users.id"],
            name=op.f("fk_settlement_periods_closed_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
            name=op.f("fk_settlement_periods_household_id_households"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settlement_periods")),
    )
    with op.batch_alter_table("settlement_periods", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_settlement_periods_household_id"), ["household_id"], unique=False
        )

    op.create_table(
        "shopping_items",
        sa.Column("household_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.Column("priority", sa.Boolean(), nullable=False),
        sa.Column("bought", sa.Boolean(), nullable=False),
        sa.Column("inserter_id", sa.Integer(), nullable=False),
        sa.Column("buyer_id", sa.Integer(), nullable=True),
        sa.Column("bought_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["buyer_id"], ["users.id"], name=op.f("fk_shopping_items_buyer_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
            name=op.f("fk_shopping_items_household_id_households"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["inserter_id"], ["users.id"], name=op.f("fk_shopping_items_inserter_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shopping_items")),
    )
    with op.batch_alter_table("shopping_items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_shopping_items_bought"), ["bought"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_shopping_items_household_id"), ["household_id"], unique=False
        )

    op.create_table(
        "chore_completions",
        sa.Column("chore_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("done_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("points_awarded", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["chore_id"],
            ["chores.id"],
            name=op.f("fk_chore_completions_chore_id_chores"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_chore_completions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chore_completions")),
    )
    with op.batch_alter_table("chore_completions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_chore_completions_chore_id"), ["chore_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_chore_completions_done_at"), ["done_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_chore_completions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "comments",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"], ["users.id"], name=op.f("fk_comments_author_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["feed_events.id"],
            name=op.f("fk_comments_event_id_feed_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comments")),
    )
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_comments_author_id"), ["author_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_comments_event_id"), ["event_id"], unique=False)

    op.create_table(
        "expenses",
        sa.Column("household_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("paid_by_id", sa.Integer(), nullable=False),
        sa.Column("spent_at", sa.Date(), nullable=False),
        sa.Column("period_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
            name=op.f("fk_expenses_household_id_households"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["paid_by_id"], ["users.id"], name=op.f("fk_expenses_paid_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["period_id"],
            ["settlement_periods.id"],
            name=op.f("fk_expenses_period_id_settlement_periods"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expenses")),
    )
    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_expenses_household_id"), ["household_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_expenses_paid_by_id"), ["paid_by_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_expenses_period_id"), ["period_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_expenses_spent_at"), ["spent_at"], unique=False)

    op.create_table(
        "likes",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["feed_events.id"],
            name=op.f("fk_likes_event_id_feed_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_likes_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_likes")),
        sa.UniqueConstraint("event_id", "user_id", name=op.f("uq_likes_event_id_user_id")),
    )
    with op.batch_alter_table("likes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_likes_event_id"), ["event_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_likes_user_id"), ["user_id"], unique=False)

    op.create_table(
        "settlement_payments",
        sa.Column("period_id", sa.Integer(), nullable=False),
        sa.Column("from_user_id", sa.Integer(), nullable=False),
        sa.Column("to_user_id", sa.Integer(), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["from_user_id"], ["users.id"], name=op.f("fk_settlement_payments_from_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["period_id"],
            ["settlement_periods.id"],
            name=op.f("fk_settlement_payments_period_id_settlement_periods"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_user_id"], ["users.id"], name=op.f("fk_settlement_payments_to_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settlement_payments")),
    )
    with op.batch_alter_table("settlement_payments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_settlement_payments_period_id"), ["period_id"], unique=False
        )

    op.create_table(
        "expense_shares",
        sa.Column("expense_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("share_cents", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["expense_id"],
            ["expenses.id"],
            name=op.f("fk_expense_shares_expense_id_expenses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_expense_shares_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expense_shares")),
        sa.UniqueConstraint(
            "expense_id", "user_id", name=op.f("uq_expense_shares_expense_id_user_id")
        ),
    )
    with op.batch_alter_table("expense_shares", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_expense_shares_expense_id"), ["expense_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_expense_shares_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # Dropping a table removes its indexes as well. Dropping them explicitly first
    # fails on MariaDB, which requires an index to stay in place while a foreign key
    # still references the column.
    op.drop_table("expense_shares")
    op.drop_table("settlement_payments")
    op.drop_table("likes")
    op.drop_table("expenses")
    op.drop_table("comments")
    op.drop_table("chore_completions")
    op.drop_table("shopping_items")
    op.drop_table("settlement_periods")
    op.drop_table("sessions")
    op.drop_table("notifications")
    op.drop_table("feed_events")
    op.drop_table("chores")
    op.drop_table("users")
    op.drop_table("households")
