"""chore completion keeps the previous state

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-03 22:37:46.133453

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chore_completions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("previous_user_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("previous_due_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_chore_completions_previous_user_id_users"),
            "users",
            ["previous_user_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chore_completions", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_chore_completions_previous_user_id_users"), type_="foreignkey"
        )
        batch_op.drop_column("previous_due_at")
        batch_op.drop_column("previous_user_id")

    # ### end Alembic commands ###
