"""completion records who booked it

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-05 22:17:07.614877

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chore_completions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("booked_by_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_chore_completions_booked_by_id_users"),
            "users",
            ["booked_by_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chore_completions", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_chore_completions_booked_by_id_users"), type_="foreignkey"
        )
        batch_op.drop_column("booked_by_id")

    # ### end Alembic commands ###
